language: python
python:
  - 2.6
  - 2.7
  - pypy
  - 3.2
  - 3.3
  - 3.4
  - nightly
  - pypy3

install:
  - python setup.py install
  - "pip install Flask==0.10.1"
  - "pip install requests==2.7.0"
script: python test_requirementsfinder.py